version: '3'
services:
  web:
    build: .
    ports:
      - "5000-5003:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis_jules:
    image: "redis:alpine"
  load_balancer:
    image: dockercloud/haproxy
    links:
      - web
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock